services:
  nginx:
    image: renatehem/dockernginx:nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "80:80"
    networks:
      - frontendnetwork
      - backendnetwork
    depends_on:
      - dockerrestapimysql
  
  dockerrestapimysql:
    image: renatehem/dockerrestapimysql:restapi 
    container_name: restapi
    build:
      context: ./DockerRestApiMySql
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - backendnetwork
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: gokstad
      MYSQL_DATABASE: productdb
    networks:
      - backendnetwork
    volumes:
      - mysql_data:/var/lib/mysql 
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  mysql_data:  

networks:
  frontendnetwork:
    driver: bridge
  backendnetwork:
    driver: bridge
